services:
  postgres:
    image: postgres:15-alpine
    container_name: postgres
    restart: unless-stopped
    environment:
      - POSTGRES_DB=oceandb
      - POSTGRES_USER=oceanuser
      - POSTGRES_PASSWORD=ocean1234
    networks:
      - ocean-network
    volumes:
      - ocean-data:/var/lib/postgresql/data
