name: ocean

include:
  - server/compose.yml
  - docker/postgres/compose.yml

volumes:
  ocean-data:
    driver: local
    name: ocean-data

networks:
  ocean-network:
    driver: bridge
    name: ocean-net

secrets:
  pg_username:
    file: ./docker/postgres/secrets/username.txt
  pg_password:
    file: ./docker/postgres/secrets/password.txt
