services:
  postgres:
    image: postgres:15-alpine
    container_name: postgres
    restart: unless-stopped
    environment:
      POSTGRES_DB: ${POSTGRES_DB:-oceandb}
      POSTGRES_USER: ${POSTGRES_USER:-oceanuser}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-oceanpass123}
    networks:
      - ocean-network
    volumes:
      - ocean-data:/var/lib/postgresql/data
